version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      storybook:
        patterns: ["storybook", "@storybook/*", "eslint-plugin-storybook"]
      vitest:
        patterns: ["vitest", "@vitest/*"]
      development:
        dependency-type: development
      runtime:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns: ["*"]
