import { writeFile } from "node:fs/promises";
import { format } from "prettier";
import { publicApi } from "./catalog.mjs";
export async function generateApi() {
  const api = publicApi();
  const md = `# Public API\n\nGenerated from TypeScript/TSDoc. Regenerated by the explorer build and manifest command.\n\n| Export | Entry | Description |\n|---|---|---|\n${api.map((x) => `| ${x.name} | ${x.entry} | ${x.description.replace(/\s+/g, " ").replace(/\|/g, "\\|")} |`).join("\n")}\n`;
  await writeFile("docs/api.md", await format(md, { parser: "markdown" }));
}
await generateApi();
